# Virtual Workspace, mainly for Vscode's Rust Analyzer to work
[workspace]
members = [
    "src-tauri",
    "library",
    "project",
    "library/macros"
]

default-members = ["src-tauri"]
resolver = "2"

