# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!


includes:
  # lib namespace, includes is used to import another taskfile
  lib:
    taskfile: ./library/Taskfile.yml
    dir: ./library

  # project namespace, includes is used to import another taskfile
  project:
    taskfile: ./project/Taskfile.yml
    dir: ./project



tasks:
  dev:
    cmds:
      - yarn tauri dev
  
  build:
      cmds:
        - yarn tauri build

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

