[package]
name = "engine_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = {path = "macros"}
id = {path = "id"}
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
ahash = "0.8.7"
anyhow = "1.0.79"
lazy_static = "1.4"

log = "0.4"
wasm-logger = "0.2"
console_error_panic_hook = "0.1"

[lib]
crate-type = ["cdylib", "rlib"]

