[package]
name = "engine_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = {path = "macros"}
id = {path = "id"}
wasm-bindgen = "0.2.84"
getrandom = { version = "0.2", features = ["js"] }

log = "0.4.6"
wasm-logger = "0.2.0"

[lib]
crate-type = ["cdylib", "rlib"]

