# https://taskfile.dev
# basically a modern makefile

version: '3'


vars:
  GREETING: Hello, World!

includes:
  # project namespace, includes is used to import another taskfile
  project:
    taskfile: ../project/Taskfile.yml
    dir: ../project

# task definitions
tasks:

  # copies the wasm from the project directory to the web directory
  copy-wasm: 
    internal: true
    cmds:
      - cp ../project/engine/wasm/* web/src/lib/wasm
  
  # copies the index.ts file from the web directory to the project directory
  copy-index-ts:
    internal: true
    cmds:
      - cp web/src/lib/wasm/index.ts ../project/engine/wasm
  build:
    cmds:
    # runs tasks in series
    - task: project:build
    - task: copy-wasm
    - task: copy-index-ts

  dev:
    dir: ./web
    cmds:
      - yarn dev

  # cargo watch
  watch:
    cmds:
      - |
        cargo watch -w src -w ../project/src -w Cargo.toml -w ../project/Cargo.toml \
        -i "web/*" -i "../project/src/engine/wasm/*" \
        -s 'task build'

  watch-all:
    # execute both tasks concurrently
    deps: [watch, dev]
  
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true